package by.itacademy.jpql.sologub.model;

public enum MilitaryRank {
    //Army
    NO_INSIGNIA, PRIVATE, PRIVATE_1ST_CLASS, CORPORAL, SPECIALIST, SERGEANT, STUFF_SERGEANT,
    SERGEANT_1ST_CLASS, MASTER_SERGEANT, FIRST_SERGEANT, SERGEANT_MAJOR, COMMAND_SERGEANT_MAJOR,
    SERGEANT_MAJOR_OF_THE_ARMY,
    //Warrant officer
    WARRANT_OFFICER_1, CHIEF_WARRANT_OFFICER_2, CHIEF_WARRANT_OFFICER_3, CHIEF_WARRANT_OFFICER_4,
    CHIEF_WARRANT_OFFICER_5,
    //Officer
    SECOND_LIEUTENANT, FIRST_LIEUTENANT, CAPTAIN, MAJOR, LIEUTENANT_COLONEL, COLONEL, BRIGADIER_GENERAL,
    MAJOR_GENERAL, LIEUTENANT_GENERAL, GENERAL, GENERAL_OF_THE_ARMY
}