package by.itacademy.jpql.sologub.model;

public enum WeaponManufacturer {
    AMERICAN_OUTDOOR_BRANDS_CORPORATION, FABRICAD_ARMI_PIETRO_BERETTA_S_P_A, FN_HERSTAL, THALES_GROUP,
    GENERAL_DYNAMICS_CORPORATION, HECHLER_AND_KOCH_GMBH, LOCKHEED_MARTIN_CORPORATION,
    NORTHROP_GRUMMAN_CORPORATION, STURM_RUGER_AND_CO_INC, TAURUS_INTERNATIONAL_MANUFACTURING_INC
}